export const MINE_MODIFY_DISPLAY = 'USER_MODIFY_DISPLAY';
export const MINE_MODIFY_INFO = 'MINE_MODIFY_INFO';
export const MINE_MODIFY_NICKNAME = 'MINE_MODIFY_NICKNAME';
export const MINE_INFO = 'MINE_INFO';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const DEPARTMENT_lIST = 'DEPARTMENT_lIST';
export const MINE_MODIFYSTORE_INFO = 'MINE_MODIFYSTORE_INFO';
