export const USER_ACCOUNT_EDIT = 'USER_ACCOUNT_EDIT';
export const USER_PASSWD_EDIT = 'USER_PASSWD_EDIT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_SET_DATA = 'USER_SET_DATA';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_REMEMBER = 'USER_SET_REMEMBER';
export const USER_ACCOUNT_CHANGE_STORE = 'USER_ACCOUNT_CHANGE_STORE';
